### PR TITLE
Haley hu patch 1

### PR DESCRIPTION
**Pull request by HaleyHu**
代码格式化：大写字母开头的方法名 --》小写字母开头

### CODE REVIEW

**Comment by HaleyHu** [comment]
`using (Decrypt())` is commented now! It dosn't work!

**Comment by erikzhang** [comment]
Have you changed the encoding of Account.java from utf-8 into gb2312?
If you change it back, and bring the braces back too, I will merge the request.

**Comment by erikzhang** [comment]
The encoding of Account.java is still gb2312? You should change it back to utf-8.

**Comment by HaleyHu** [comment]
The encoding of Account.java is wrong now? But I never change it. I modify the file in github.com and the submit them.

**Comment by erikzhang** [comment]
> The encoding of Account.java is wrong now? But I never change it. I modify the file in github.com and the submit them.

Yes, it should be utf8. But in your commit, it is gb2312.

**Pull request closed without merging**
